import { Resend } from "resend";

export default async function handler(req: any, res: any) {
  if (req.method !== "POST") {
    return res.status(405).json({
      success: false,
      error: "Method not allowed",
    });
  }

  try {
    const {
      email,
      type,
      companyName,
      city,
      industry,
      phone,
    } = req.body;

    if (!email || !type || !industry || !phone) {
      return res.status(400).json({
        success: false,
        error: "Missing required fields",
      });
    }

    const apiKey = process.env.RESEND_API_KEY;

    if (!apiKey) {
      console.error("RESEND_API_KEY is missing.");

      return res.status(500).json({
        success: false,
        error: "RESEND_API_KEY is not configured.",
      });
    }

    const resend = new Resend(apiKey);

    const recipient = "info@karotradz.com";

    const cc = [
      "govindaraj.poosamani@karotradz.com",
       "sales@karotradz.com",
       "support@karotradz.com",
    ];

    const subject = `KaroTradz - New Inquiry: ${
      type === "manufacturer"
        ? "Manufacturer"
        : "Buyer"
    } - ${industry}`;

    const htmlContent = `
<div style="font-family:Poppins,Arial,sans-serif;max-width:700px;margin:auto;background:#ffffff;border:1px solid #e5e7eb;border-radius:8px;padding:30px;">

<h2 style="color:#ea580c;margin-top:0;">
KaroTradz - New Inquiry Received
</h2>

<p>
A new enquiry has been submitted from the KaroTradz website.
</p>

<table style="width:100%;border-collapse:collapse;">

<tr style="background:#f3f4f6;">
<td style="padding:10px;font-weight:bold;width:180px;">
Inquiry Type
</td>
<td style="padding:10px;">
${type}
</td>
</tr>

<tr>
<td style="padding:10px;font-weight:bold;">
Industry
</td>
<td style="padding:10px;">
${industry}
</td>
</tr>

<tr style="background:#f3f4f6;">
<td style="padding:10px;font-weight:bold;">
Email
</td>
<td style="padding:10px;">
<a href="mailto:${email}">
${email}
</a>
</td>
</tr>

<tr>
<td style="padding:10px;font-weight:bold;">
Phone
</td>
<td style="padding:10px;">
<a href="tel:${phone.replace(/\s+/g, "")}">
${phone}
</a>
</td>
</tr>

${
  companyName
    ? `
<tr style="background:#f3f4f6;">
<td style="padding:10px;font-weight:bold;">
Company
</td>
<td style="padding:10px;">
${companyName}
</td>
</tr>
`
    : ""
}

${
  city
    ? `
<tr>
<td style="padding:10px;font-weight:bold;">
City
</td>
<td style="padding:10px;">
${city}
</td>
</tr>
`
    : ""
}

</table>

<div style="margin-top:25px;padding:15px;background:#eff6ff;border-left:4px solid #3b82f6;">

Click the email or phone number above to contact the lead directly.

</div>

<p style="font-size:12px;color:#888;margin-top:30px;">
This is an automated email generated by the KaroTradz website.
</p>

</div>
`;

    const greeting = "Hi,";

    const thankYouSubject =
      "Thanks for your interest in KaroTradz";

    const manufacturerTemplate = `
<div style="font-family:Arial,sans-serif;max-width:650px;margin:auto;padding:30px;color:#333;line-height:1.7;">

<h2 style="color:#ea580c;">
Thanks for your interest in KaroTradz
</h2>

<p>${greeting}</p>

<p>
Thank you for contacting
<strong>KaroTradz</strong>.
</p>

<p>

We're building a platform that helps Indian manufacturers connect directly with verified global buyers while providing complete cost transparency before business begins.

</p>

<p>

We are currently speaking with manufacturers to understand export challenges and improve the platform based on real business needs.

</p>

<p>

Our team will contact you within
<strong>2 business days</strong>.

</p>

<p>

If you have anything you'd like to add, simply reply to this email.

</p>

<br>

Regards,

<br><br>

<b>KaroTradz Team</b>

<br>

info@karotradz.com

<hr>

<p style="font-size:12px;color:#888;">

This email was sent automatically because you contacted KaroTradz.

</p>

</div>
`;

    const buyerTemplate = `
<div style="font-family:Arial,sans-serif;max-width:650px;margin:auto;padding:30px;color:#333;line-height:1.7;">

<h2 style="color:#ea580c;">
Thanks for your interest in KaroTradz
</h2>

<p>${greeting}</p>

<p>

Thank you for contacting
<strong>KaroTradz</strong>.

</p>

<p>

KaroTradz helps global buyers connect with verified Indian manufacturers while providing complete landed-cost transparency before any commitment.

</p>

<p>

We're speaking with buyers around the world to understand sourcing challenges and improve the platform before launch.

</p>

<p>

Our team will contact you within
<strong>2 business days</strong>.

</p>

<p>

If you have additional information, simply reply to this email.

</p>

<br>

Regards,

<br><br>

<b>KaroTradz Team</b>

<br>

info@karotradz.com

<hr>

<p style="font-size:12px;color:#888;">

This email was sent automatically because you contacted KaroTradz.

</p>

</div>
`;

    console.log("Sending admin notification...");

    const adminEmail = await resend.emails.send({
      from: "KaroTradz Inquiry <info@karotradz.com>",
      to: recipient,
      cc,
      subject,
      html: htmlContent,
    });

    console.log(
      "Admin email response:",
      JSON.stringify(adminEmail, null, 2)
    );

    if ((adminEmail as any)?.error) {
      throw new Error(
        JSON.stringify((adminEmail as any).error)
      );
    }

    console.log("Sending thank-you email...");

    const thankYouEmail = await resend.emails.send({
      from: "KaroTradz <info@karotradz.com>",
      to: email,
      subject: thankYouSubject,
      html:
        type === "manufacturer"
          ? manufacturerTemplate
          : buyerTemplate,
    });

    console.log(
      "Thank-you response:",
      JSON.stringify(thankYouEmail, null, 2)
    );

    if ((thankYouEmail as any)?.error) {
      throw new Error(
        JSON.stringify((thankYouEmail as any).error)
      );
    }

    return res.status(200).json({
      success: true,
      message: "Emails sent successfully.",
      adminEmail,
      thankYouEmail,
    });
  } catch (error: any) {
    console.error("====================================");
    console.error("EMAIL SEND FAILED");
    console.error(error);
    console.error("====================================");

    return res.status(500).json({
      success: false,
      error: "Failed to dispatch email.",
      details:
        error?.message ||
        JSON.stringify(error) ||
        String(error),
    });
  }
}